### ISSUE TITLE
Add commas to the badge output

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#1]
### Issue

The YouTube Data API stores numbers without commas. When creating the badge, Shields.io handles the creation of the badge from the point of passing the URL onward. The task of this issue is to ensure that commas will get added to the badge that is generated.

### Two different approaches

One way you could approach this problem is by implementing the YouTube Data API calls within the PHP code, add commas to the resulting number (for example, using `number_format()`). Use the retrieved information to make a "static" Shields.io badge.

The second approach would be to run a replacement on the string returned by the `curl_get_contents()` function.

Whichever method of implementing the feature you choose is fine.

### Expected outcome

Before implementing the change:

![image](https://user-images.githubusercontent.com/20955511/95364729-dcc8ba80-08d9-11eb-8cec-b3b02ffa691f.png)

After implementing the change:

![image](https://user-images.githubusercontent.com/20955511/95364795-efdb8a80-08d9-11eb-9cd4-7e10b5debfee.png)

**Comment by iamsriranga** [comment]
@DenverCoder1 , can i work on it

**Comment by DenverCoder1** [comment]
Hi, @saideepesh000 I would appreciate it. Thanks!
If you have any questions, don't hesitate to ask.

**Comment by DenverCoder1** [comment]
Hi @saideepesh000, It's been over a day and it doesn't seem like you have forked the project. I'm going to allow another user to contribute to this issue. I hope to create more opportunities for contributions soon.
