### ISSUE TITLE
Short number formatted labels appear stretched for large numbers

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#11]
### Issue

Currently, the number is updated with a regex replacement on the response from Shields.io. The rectangle width and text length don't get updated, causing the text to occasionally appear stretched like shown here:

![image](https://user-images.githubusercontent.com/20955511/95563365-f7a84580-0a25-11eb-9397-380832e71503.png)

### Potential fixes

The easiest fix might be to be to fetch the YouTube statistics before creating the shields.io URL and use the static shields.io API instead of dynamic. Doing it this way will allow shields.io to determine what the rectangle size and text length should be.

The format for the static shields.io URLs is like this:

`https://img.shields.io/static/v1?label=<LABEL>&message=<MESSAGE>&color=<COLOR>`

Other query parameters such as `labelColor`, `style`, and others will still work.

#### Steps

* Fetch the data from the YouTube API with `curl_get_contents` and `json_decode`
* Locate the view count and subscriber count numbers using array indexing
* Set the `message` parameter to the number, but make sure the number is in the right format first
* Remove unused code

If you are able to accurately resize the input another way, feel free to do it as you choose.

If you have any questions, don't hesitate to ask!

----

Please comment on the issue before making a pull request.

This issue is for first-timers only! Since this a simple issue to fix, I am offering this issue specifically to those who have submitted fewer than 4 pull requests

**Comment by DavidPretty** [comment]
Can I take this

**Comment by DenverCoder1** [comment]
@DavidPretty Sure, that would be great!

**Comment by ImagineZero0** [comment]
Can I work on this.?

**Comment by DenverCoder1** [comment]
@ImagineZero0, the issue has already been claimed by @DavidPretty although I'm not sure how much progress has been made. If there has been no progress and no response by this time tomorrow, I will make it available.

**Comment by DenverCoder1** [comment]
@DavidPretty If you have any questions, don't hesitate to ask. Let me know if you plan on working on this.

**Comment by ImagineZero0** [comment]
Okay @DenverCoder1

**Comment by DavidPretty** [comment]
> @DavidPretty If you have any questions, don't hesitate to ask. Let me know if you plan on working on this.

HI, was going to look at this tomorrow. If that's not Ok happy for someone else to claim

**Comment by DenverCoder1** [comment]
@DavidPretty 👍 Not a problem at all. You can take your time. I just wanted to make sure it wasn't forgotten about.

**Comment by DavidPretty** [comment]
Sorry, relinquishing this, apologies for wasting people's time

**Comment by DenverCoder1** [comment]
@DavidPretty I'm able to help with some steps if you need, but if you're sure, I can see if @ImagineZero0 is still interested.

**Comment by DavidPretty** [comment]
HI DenverCoder1 thanks for the offer but I don't have enough php experience-should have looked more closely before jumping in. Please let ImagineZero0 take this.

**Comment by DenverCoder1** [comment]
@ImagineZero0 This issue is available now, let me know if you are still interested

**Comment by ImagineZero0** [comment]
Yes, I would really love to contribute.
Thank you

**Comment by DenverCoder1** [comment]
@ImagineZero0 You can work on it if you'd like.
If you have any questions, don't hesitate to ask!

**Comment by ImagineZero0** [comment]
Okay, Sure @DenverCoder1 ...
I will get straight on it.

**Comment by ImagineZero0** [comment]
Hey, @DenverCoder1, I just wanted your help in the part of `curl_get_contents`  as it kind of seems not trivial, and also I am not able to understand how to use it get the required JSON data from the API, but after that, I got how to change the dynamic Shields.io to Static shield.io...
kindly look into this.

**Comment by DenverCoder1** [comment]
Hi @ImagineZero0!

In functions.php, you should see `curl_get_contents`. All you need to know about it is that it takes a url as a parameter and returns the response text of the url as the output (whether it is JSON, an SVG image, or whatever it is).

You can use `curl_get_contents` on the YouTube API url to get the JSON returned as a string, then `json_decode` can be used on that to turn it into a PHP array which can be parsed more easily.

Let me know if that helps

**Comment by ImagineZero0** [comment]
Hey @DenverCoder1, Your advice worked out and I was able to do almost all the steps that is extracting the Json from the API, decoding and extracting the required array values, made  the count in a proper format, and build the shield static URL, but when I am trying to run with the `header('Content-type: image/svg+xml');` code, it is giving me a Render Error, while without this I am getting the URL as output from echo(which I would get),
_https://img.shields.io/static/v1?label=Youtube+Subscribers&message=107m&color=brightgreen&logo=youtube&logoColor=white&style=flat-square&labelColor=gray&id=UC-lHJZR3Gqxm24_Vd_AJ5Yw&key=AIzaSyB66QFKg2skV3gGHDnNHJotxmMgKfy5k9E_

But I am not able to render this..

Could you have a look at this..

I have attached a photo of my code for the index.php for Subscribers Count..

![2020-10-19](https://user-images.githubusercontent.com/68947540/96482268-615ff500-1259-11eb-99ee-383f12bd1e3d.png)

**Comment by DenverCoder1** [comment]
@ImagineZero0 To output the image and not the url, you can use `curl_get_contents` on the image url and echo the contents.

**Comment by ImagineZero0** [comment]
Thank you @DenverCoder1, I have successfully changed the code and verified it. I have made the respective PR, please review it.

Thank you again for your advice and help...

**Comment by DenverCoder1** [comment]
Fixed with #17
