### ISSUE TITLE
Add return types to function declarations

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#3]
PHP code is more manageable when return types are declared.

To fix this issue, make a pull request with the return type specified for each function.

Reference: https://www.tutorialspoint.com/php7/php7_returntype_declarations.htm

This issue is for first-timers only! Since this a simple issue to fix, I am offering this issue specifically to those who have submitted fewer than 4 pull requests

**Comment by jlolzzz** [comment]
Hello, I would like to help out with this issue.

**Comment by DenverCoder1** [comment]
@currywurstjake Great!
If you have any questions, don't hesitate to ask!

**Comment by adi-mohan** [comment]
@DenverCoder1 Please assign this issue to me.

**Comment by DenverCoder1** [comment]
@adi-mohan It was requested already by @currywurstjake. I'll give them a chance first.

**Comment by DenverCoder1** [comment]
@currywurstjake Please let me know if you plan on working on this.

**Comment by jlolzzz** [comment]
@DenverCoder1 Sorry for the delay. I believe I have it, but when I go to test i keep getting getting an invalid or missing API key response. I am hoping to figure that out today - shortly.

**Comment by DenverCoder1** [comment]
Yeah, an API key is required for accessing the YouTube Data API. I put instructions here for making one: https://github.com/DenverCoder1/github-readme-youtube-stats#how-to-get-a-youtube-api-key

**Comment by DenverCoder1** [comment]
@currywurstjake If you see that message, that means the code is running properly. If you would rather not set up an API key and you think there are no issues, you can push the changes and I can take a look at it.

**Comment by jlolzzz** [comment]
Ok no worries, I will push changes in a minute.

**Comment by DenverCoder1** [comment]
Fixed with #14
