### ISSUE TITLE
Add new display option: short numbers

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#4]
Add an optional url parameter called `format` which will allow users to select between 3 formats of numbers:

* `format=none`

![image](https://user-images.githubusercontent.com/20955511/95502850-2a652600-09b3-11eb-9e44-43897ca577b3.png)

* `format=commas`

![image](https://user-images.githubusercontent.com/20955511/95502999-613b3c00-09b3-11eb-854b-f8e4c1d1a16f.png)

* `format=short`

![image](https://user-images.githubusercontent.com/20955511/95503055-77e19300-09b3-11eb-95ff-348b1eb7e60f.png)

Commas is already implemented by #2.

### Issues

* Implement a short numbers function to convert numbers to a rounded form (ex. 3.5k, 6.8m, 9.1b)

> Suggested reference: https://stackoverflow.com/a/52490452/11608064

* Implement a url parameter to allow choosing between different number formats (ex. `format=commas`, `format=short`)

* If the parameter is not specified, the default value that should be used is `short`

----

This issue is for first-timers only! Since this a simple issue to fix, I am offering this issue specifically to those who have submitted fewer than 4 pull requests

**Comment by tim-richter** [comment]
Hi @DenverCoder1 , I could give this a shot!

**Comment by DenverCoder1** [comment]
@tim-richter That would be great!
If you have any questions, don't hesitate to ask.

**Comment by Itachi8374** [comment]
Hi, I am new to open source. I would like to fix this issue @DenverCoder1

**Comment by DenverCoder1** [comment]
Hi @Itachi8374, this issue has already been fixed, by I will be opening more issues that you can contribute to. Thanks!
