### ISSUE TITLE
Add documentation for the format parameter

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#7]
### Issue

With #4 and #5, a new url parameter was introduced call `format`.

See the relevant issues for the details of what this parameter does and what the options are.

There is not yet a section in the README explaining how to use it.

Following the style of other parameter explanations, the documentation for this new parameter should be added.

----

Please comment on the issue before making a pull request.

This issue is for first-timers only! Since this a simple issue to fix, I am offering this issue specifically to those who have submitted fewer than 4 pull requests

**Comment by patidar-jaishree** [comment]
Hi, I am new to open source. I would like to fix this issue @DenverCoder1

**Comment by DenverCoder1** [comment]
@patidar-jaishree That would be much appreciated!
If you have any questions, don't hesitate to ask!

**Comment by patidar-jaishree** [comment]
@DenverCoder1 I have added format parameter in the README. 
Please verify my commit and let me know if I need to add more details (regex or something else) otherwise I will raise a pull request for the same.

**Comment by DenverCoder1** [comment]
@patidar-jaishree Looks good! I would remove the `label=123` and make them all have the same label. The mention of `label=123` in the PR was about a bug which can be fixed later.

**Comment by patidar-jaishree** [comment]
@DenverCoder1 Removed label and raised a PR

**Comment by DenverCoder1** [comment]
👍 Fixed with #12
