### ISSUE TITLE
Uppercase letters when using for-the-badge style

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#8]
### Issue

The `for-the-badge` style should use uppercase letters for the label and message.

### What it currently does

The `k` is lowercase:

![image](https://user-images.githubusercontent.com/20955511/95554358-b9585980-0a18-11eb-89ab-92d19ff315a8.png)

### What it should do

The `k` should be capitalized:

![image](https://user-images.githubusercontent.com/20955511/95554512-f886aa80-0a18-11eb-8920-0625710194ed.png)

Other styles should continue to use lowercase letters:

![image](https://user-images.githubusercontent.com/20955511/95554682-43a0bd80-0a19-11eb-8be9-89ca907589fa.png)

----

Please comment on the issue before making a pull request.

This issue is for first-timers only! Since this a simple issue to fix, I am offering this issue specifically to those who have submitted fewer than 4 pull requests

**Comment by bofalke** [comment]
I'd like to give it a shot (:

**Comment by DenverCoder1** [comment]
@bofalke Awesome!
If you have any questions, don't hesitate to ask!

**Comment by bofalke** [comment]
I cannot see the part where the query parameters are overwriting the default array. Maybe you can give me a small hint on this one? Or is this part of the issue here?

**Comment by DenverCoder1** [comment]
@bofalke In the get shields url function (in web/functions.php) there are calls to validateParam to check parameters like style. The number format changing currently happens at the end with the call to format response number. At that point, you can check the style parameter and capitalize it after formatting.

**Comment by bofalke** [comment]
Ah i missed that the `validateParam` function was returning the values from the request if set. Thanks (:
