### ISSUE TITLE
Allow hyphens and underscores in Channel ID

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-stats#9]
### Issue

When validating the ID parameter, hyphens and underscores are considered not valid making it give the wrong channel info.

Some channel IDs, such as `UC-lHJZR3Gqxm24_Vd_AJ5Yw`, contain hyphens and underscores and should be allowed.

You will need to modify the regex for validating the ID to allow underscores and hyphens.

----

Leave a comment if you plan on fixing this

**Comment by saptarsi96** [comment]
Hi, Can I work on this?

**Comment by adi-mohan** [comment]
I am planning on fixing this. First timer here. #hacktoberfest

**Comment by DenverCoder1** [comment]
@adi-mohan Great!
If you have any questions, let me know!

**Comment by SaiSrichandra** [comment]
I would like to give it a shot

**Comment by adi-mohan** [comment]
I had just created a pull request for the issue. Please have a look.

**Comment by DenverCoder1** [comment]
Fixed with #10
